// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menu-open-preferences'
  | 'menu-sync-collection'
  | 'menu-sync-item'
  | 'pref-create-index'
  | 'pref-fields-title'
  | 'pref-file-name-strategy'
  | 'pref-help'
  | 'pref-output-folder'
  | 'pref-page-title'
  | 'pref-save'
  | 'pref-save-success'
  | 'pref-sync-help'
  | 'pref-sync-on-modify'
  | 'pref-sync-title'
  | 'pref-title'
  | 'pref-vault-browse'
  | 'pref-vault-path'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
