// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "vaultPath": string;
      "outputFolder": string;
      "syncOnModify": boolean;
      "createDataviewIndex": boolean;
      "fileNameStrategy": string;
      "selectedFields": string;
      "collectionSyncConfigs": string;
    };
  }
}
